use SWP391;
insert into subject(subjectName,[level]) values('Literature',1);
insert into subject(subjectName,[level]) values('Mathematics',1);
insert into subject(subjectName,[level]) values('Ethics',1);
insert into subject(subjectName,[level]) values('Sociology',1);
insert into subject(subjectName,[level]) values('Music',1);
insert into subject(subjectName,[level]) values('Fine Arts',1);
insert into subject(subjectName,[level]) values('Physical Education',1);

insert into subject(subjectName,[level]) values('Literature',2);
insert into subject(subjectName,[level]) values('Mathematics',2);
insert into subject(subjectName,[level]) values('Ethics',2);
insert into subject(subjectName,[level]) values('Sociology',2);
insert into subject(subjectName,[level]) values('Music',2);
insert into subject(subjectName,[level]) values('Fine Arts',2);
insert into subject(subjectName,[level]) values('Physical Education',2);

insert into subject(subjectName,[level]) values('Literature',3);
insert into subject(subjectName,[level]) values('Mathematics',3);
insert into subject(subjectName,[level]) values('Ethics',3);
insert into subject(subjectName,[level]) values('Sociology',3);
insert into subject(subjectName,[level]) values('Music',3);
insert into subject(subjectName,[level]) values('Fine Arts',3);
insert into subject(subjectName,[level]) values('Physical Education',3);
insert into subject(subjectName,[level]) values('Technology',3);
insert into subject(subjectName,[level]) values('Informatics',3);

insert into subject(subjectName,[level]) values('Literature',4);
insert into subject(subjectName,[level]) values('Mathematics',4);
insert into subject(subjectName,[level]) values('Ethics',4);
insert into subject(subjectName,[level]) values('History',4);
insert into subject(subjectName,[level]) values('Geography',4);
insert into subject(subjectName,[level]) values('Science',4);
insert into subject(subjectName,[level]) values('Music',4);
insert into subject(subjectName,[level]) values('Fine Arts',4);
insert into subject(subjectName,[level]) values('Physical Education',4);
insert into subject(subjectName,[level]) values('Technology',4);
insert into subject(subjectName,[level]) values('Informatics',4);

insert into subject(subjectName,[level]) values('Literature',5);
insert into subject(subjectName,[level]) values('Mathematics',5);
insert into subject(subjectName,[level]) values('Ethics',5);
insert into subject(subjectName,[level]) values('History',5);
insert into subject(subjectName,[level]) values('Geography',5);
insert into subject(subjectName,[level]) values('Science',5);
insert into subject(subjectName,[level]) values('Music',5);
insert into subject(subjectName,[level]) values('Fine Arts',5);
insert into subject(subjectName,[level]) values('Physical Education',5);
insert into subject(subjectName,[level]) values('Technology',5);
insert into subject(subjectName,[level]) values('Informatics',5);

insert into subject(subjectName,[level]) values('Literature',6);
insert into subject(subjectName,[level]) values('Mathematics',6);
insert into subject(subjectName,[level]) values('Ethics',6);
insert into subject(subjectName,[level]) values('History',6);
insert into subject(subjectName,[level]) values('Geography',6);
insert into subject(subjectName,[level]) values('Science',6);
insert into subject(subjectName,[level]) values('Physics',6);
insert into subject(subjectName,[level]) values('Biology',6);
insert into subject(subjectName,[level]) values('Music',6);
insert into subject(subjectName,[level]) values('Fine Arts',6);
insert into subject(subjectName,[level]) values('Physical Education',6);
insert into subject(subjectName,[level]) values('Technology',6);
insert into subject(subjectName,[level]) values('Informatics',6);

insert into subject(subjectName,[level]) values('Literature',7);
insert into subject(subjectName,[level]) values('Mathematics',7);
insert into subject(subjectName,[level]) values('Ethics',7);
insert into subject(subjectName,[level]) values('History',7);
insert into subject(subjectName,[level]) values('Geography',7);
insert into subject(subjectName,[level]) values('Science',7);
insert into subject(subjectName,[level]) values('Physics',7);
insert into subject(subjectName,[level]) values('Biology',7);
insert into subject(subjectName,[level]) values('Music',7);
insert into subject(subjectName,[level]) values('Fine Arts',7);
insert into subject(subjectName,[level]) values('Physical Education',7);
insert into subject(subjectName,[level]) values('Technology',7);
insert into subject(subjectName,[level]) values('Informatics',7);

insert into subject(subjectName,[level]) values('Literature',8);
insert into subject(subjectName,[level]) values('Mathematics',8);
insert into subject(subjectName,[level]) values('Ethics',8);
insert into subject(subjectName,[level]) values('History',8);
insert into subject(subjectName,[level]) values('Geography',8);
insert into subject(subjectName,[level]) values('Science',8);
insert into subject(subjectName,[level]) values('Physics',8);
insert into subject(subjectName,[level]) values('Chemistry',8);
insert into subject(subjectName,[level]) values('Biology',8);
insert into subject(subjectName,[level]) values('Music',8);
insert into subject(subjectName,[level]) values('Fine Arts',8);
insert into subject(subjectName,[level]) values('Physical Education',8);
insert into subject(subjectName,[level]) values('Technology',8);
insert into subject(subjectName,[level]) values('Informatics',8);

insert into subject(subjectName,[level]) values('Literature',9);
insert into subject(subjectName,[level]) values('Mathematics',9);
insert into subject(subjectName,[level]) values('Ethics',9);
insert into subject(subjectName,[level]) values('History',9);
insert into subject(subjectName,[level]) values('Geography',9);
insert into subject(subjectName,[level]) values('Science',9);
insert into subject(subjectName,[level]) values('Physics',9);
insert into subject(subjectName,[level]) values('Chemistry',9);
insert into subject(subjectName,[level]) values('Biology',9);
insert into subject(subjectName,[level]) values('Music',9);
insert into subject(subjectName,[level]) values('Fine Arts',9);
insert into subject(subjectName,[level]) values('Physical Education',9);
insert into subject(subjectName,[level]) values('Technology',9);
insert into subject(subjectName,[level]) values('Informatics',9);

insert into subject(subjectName,[level]) values('Literature',10);
insert into subject(subjectName,[level]) values('Mathematics',10);
insert into subject(subjectName,[level]) values('Ethics',10);
insert into subject(subjectName,[level]) values('History',10);
insert into subject(subjectName,[level]) values('Geography',10);
insert into subject(subjectName,[level]) values('Science',10);
insert into subject(subjectName,[level]) values('Physics',10);
insert into subject(subjectName,[level]) values('Chemistry',10);
insert into subject(subjectName,[level]) values('Biology',10);
insert into subject(subjectName,[level]) values('Music',10);
insert into subject(subjectName,[level]) values('Fine Arts',10);
insert into subject(subjectName,[level]) values('Physical Education',10);
insert into subject(subjectName,[level]) values('Technology',10);
insert into subject(subjectName,[level]) values('Informatics',10);

insert into subject(subjectName,[level]) values('Literature',11);
insert into subject(subjectName,[level]) values('Mathematics',11);
insert into subject(subjectName,[level]) values('Ethics',11);
insert into subject(subjectName,[level]) values('History',11);
insert into subject(subjectName,[level]) values('Geography',11);
insert into subject(subjectName,[level]) values('Science',11);
insert into subject(subjectName,[level]) values('Physics',11);
insert into subject(subjectName,[level]) values('Chemistry',11);
insert into subject(subjectName,[level]) values('Biology',11);
insert into subject(subjectName,[level]) values('Music',11);
insert into subject(subjectName,[level]) values('Fine Arts',11);
insert into subject(subjectName,[level]) values('Physical Education',11);
insert into subject(subjectName,[level]) values('Technology',11);
insert into subject(subjectName,[level]) values('Informatics',11);

insert into subject(subjectName,[level]) values('Literature',12);
insert into subject(subjectName,[level]) values('Mathematics',12);
insert into subject(subjectName,[level]) values('Ethics',12);
insert into subject(subjectName,[level]) values('History',12);
insert into subject(subjectName,[level]) values('Geography',12);
insert into subject(subjectName,[level]) values('Science',12);
insert into subject(subjectName,[level]) values('Physics',12);
insert into subject(subjectName,[level]) values('Chemistry',12);
insert into subject(subjectName,[level]) values('Biology',12);
insert into subject(subjectName,[level]) values('Music',12);
insert into subject(subjectName,[level]) values('Fine Arts',12);
insert into subject(subjectName,[level]) values('Physical Education',12);
insert into subject(subjectName,[level]) values('Technology',12);
insert into subject(subjectName,[level]) values('Informatics',12);